# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat_order',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
